import { requireAuthContext } from '@/lib/auth-context'
import { dateOnly, dateTime, money, hermosilloTodayKey } from '@/lib/format'
import { getFinancialSummary } from '@/lib/financial-summary'
import { isAdministrator } from '@/lib/admin-access'
import PaymentForm from '@/components/payment-form'

type SearchParams=Promise<Record<string,string|string[]|undefined>>
function defaultStart(){const d=new Date(`${hermosilloTodayKey()}T12:00:00-07:00`);d.setDate(1);return d.toISOString().slice(0,10)}

export default async function CobranzaPage({searchParams}:{searchParams:SearchParams}){
 const params=await searchParams,context=await requireAuthContext(),administrator=isAdministrator(context.role)
 const financial=await getFinancialSummary(context.supabase,context.organizationId)
 const from=typeof params.from==='string'?params.from:defaultStart(),to=typeof params.to==='string'?params.to:hermosilloTodayKey()
 let periodPayments:any[]=[]
 if(administrator){const {data}=await context.supabase.from('payments').select('id, amount, payment_date, payment_method, reference, processes(service_name, clients(full_name))').eq('organization_id',context.organizationId).gte('payment_date',`${from}T00:00:00-07:00`).lte('payment_date',`${to}T23:59:59-07:00`).order('payment_date',{ascending:false});periodPayments=data??[]}
 const periodTotal=periodPayments.reduce((s,p)=>s+Number(p.amount),0),periodAverage=periodPayments.length?periodTotal/periodPayments.length:0
 const methods=new Map<string,number>();periodPayments.forEach(p=>methods.set(p.payment_method||'Otro',(methods.get(p.payment_method||'Otro')??0)+Number(p.amount)))
 return <><header className="page-header"><div><span className="eyebrow">Control financiero</span><h1>Cobranza</h1><p>Pagos, saldos y compromisos en tiempo real.</p></div></header>
 {params.created?<div className="notice success">Pago registrado correctamente.</div>:null}{params.error?<div className="notice error">{String(params.error)}</div>:null}
 {administrator?<section className="panel-card executive-range-panel"><div className="panel-heading"><div><span className="eyebrow">Solo administrador</span><h3>Ingresos por intervalo</h3></div></div><form className="date-range-form" method="get"><label>Desde<input type="date" name="from" defaultValue={from}/></label><label>Hasta<input type="date" name="to" defaultValue={to}/></label><button className="primary-button" type="submit">Consultar</button></form><div className="client-kpis"><article><span>Cobrado</span><strong>{money(periodTotal)}</strong></article><article><span>Pagos</span><strong>{periodPayments.length}</strong></article><article><span>Ticket promedio</span><strong>{money(periodAverage)}</strong></article><article><span>Periodo</span><strong className="small-kpi">{dateOnly(`${from}T12:00:00-07:00`)}–{dateOnly(`${to}T12:00:00-07:00`)}</strong></article></div><div className="payment-method-summary">{[...methods.entries()].map(([method,total])=><div key={method}><span>{method}</span><strong>{money(total)}</strong></div>)}</div><div className="activity-list compact">{periodPayments.slice(0,50).map((p:any)=>{const process=Array.isArray(p.processes)?p.processes[0]:p.processes,client=Array.isArray(process?.clients)?process.clients[0]:process?.clients;return <div key={p.id}><strong>{money(p.amount)} · {client?.full_name||'Cliente'}</strong><small>{dateTime(p.payment_date)} · {process?.service_name||'Sin trámite'} · {p.payment_method}</small></div>})}{!periodPayments.length?<div className="empty-state">Sin ingresos en el periodo seleccionado.</div>:null}</div></section>:null}
 <section className="client-kpis"><article><span>Total acordado</span><strong>{money(financial.totalAgreed)}</strong></article><article><span>Cobrado histórico</span><strong>{money(financial.totalPaid)}</strong></article><article><span>Por cobrar</span><strong>{money(financial.totalBalance)}</strong></article><article><span>Vencido</span><strong>{money(financial.overdueBalance)}</strong></article></section>
 <section className="collections-layout"><PaymentForm processes={financial.rows.filter(r=>r.balance>0).map(r=>{const c=Array.isArray(r.clients)?r.clients[0]:r.clients;return{id:r.id,service_name:r.service_name,client_name:c?.full_name||'Cliente',balance:r.balance}})}/><section className="table-card"><div className="panel-heading"><div><span className="eyebrow">Cuentas</span><h3>Estado de cobranza</h3></div><strong>{financial.rows.length}</strong></div><div className="collection-cards">{financial.rows.map(row=>{const c=Array.isArray(row.clients)?row.clients[0]:row.clients;return <article className={row.overdue?'collection-card overdue':'collection-card'} key={row.id}><div className="collection-card-head"><div><strong>{c?.full_name||'Cliente'}</strong><small>{row.service_name} · {c?.phone||''}</small></div><span className={row.balance<=0?'payment-status paid':row.paid>0?'payment-status partial':'payment-status pending'}>{row.balance<=0?'Pagado':row.paid>0?'Parcial':'Pendiente'}</span></div><div className="collection-amounts"><div><span>Total</span><strong>{money(row.agreed)}</strong></div><div><span>Pagado</span><strong>{money(row.paid)}</strong></div><div><span>Saldo</span><strong>{money(row.balance)}</strong></div></div><small>Compromiso: {row.commitment||'Sin fecha'}{row.overdue?' · VENCIDO':''}</small></article>})}</div></section></section>
 </>
}
