import { requireAuthContext } from '@/lib/auth-context'
import { requireAdministrator } from '@/lib/admin-access'
import { getInsightsData, bonusForRevenue } from '@/lib/insights'
import { money } from '@/lib/format'
import { saveBonusRule } from '../actions'

type SearchParams = Promise<Record<string,string|string[]|undefined>>
export default async function BonusesPage({searchParams}:{searchParams:SearchParams}){const params=await searchParams;const context=await requireAuthContext();requireAdministrator(context);const data=await getInsightsData(context.supabase,context.organizationId);return <><header className="page-header"><div><span className="eyebrow">Águila Insights</span><h1>Metas y bonos del equipo</h1><p>El cálculo utiliza únicamente pagos efectivamente registrados en Cobranza.</p></div></header>{params.saved?<div className="notice success">Regla de bono guardada.</div>:null}{params.error?<div className="notice error">{String(params.error)}</div>:null}
<section className="insights-grid"><form action={saveBonusRule} className="panel-card insight-form"><div className="panel-heading"><div><span className="eyebrow">Nueva regla</span><h3>Bono semanal</h3></div></div><label>Usuario<select name="user_id" required><option value="">Seleccionar</option>{data.profiles.map((p:any)=><option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label><label>Nombre<input name="name" defaultValue="Bono semanal por ingresos cobrados"/></label><div className="form-grid"><label>Meta para activar<input name="threshold_amount" type="number" defaultValue="17000" min="1"/></label><label>Bono base<input name="base_bonus" type="number" defaultValue="1000" min="0"/></label><label>Cada cuánto adicional<input name="step_amount" type="number" defaultValue="1000" min="1"/></label><label>Bono por bloque<input name="step_bonus" type="number" defaultValue="100" min="0"/></label></div><div className="readonly-rule">Fuente: <strong>Dinero cobrado</strong> · Periodo: <strong>Semanal</strong></div><button className="primary-button">Guardar regla</button></form>
<article className="panel-card"><div className="panel-heading"><div><span className="eyebrow">Semana actual</span><h3>Bonos estimados</h3></div><strong>{money(data.weekRevenue)}</strong></div><div className="bonus-rule-list">{data.bonusRules.map((r:any)=>{const p=Array.isArray(r.profiles)?r.profiles[0]:r.profiles;const bonus=bonusForRevenue(data.weekRevenue,Number(r.threshold_amount),Number(r.base_bonus),Number(r.step_amount),Number(r.step_bonus));const progress=Math.min(100,Math.round(data.weekRevenue/Number(r.threshold_amount)*100));return <article key={r.id}><div><span><strong>{p?.full_name??'Usuario'}</strong><small>{r.name}</small></span><strong>{money(bonus)}</strong></div><div className="progress-track"><span style={{width:`${progress}%`}}/></div><small>{money(data.weekRevenue)} cobrados de {money(Number(r.threshold_amount))} para activar el bono.</small></article>})}{!data.bonusRules.length?<div className="empty-state">Configura la regla de Mariana.</div>:null}</div></article></section></>}
